---

stages:
  - linting

ansible-lint:
  image: quay.io/ansible/creator-ee:latest
  stage: linting
  script:
    - ansible-lint --force-color -p *

yamllint:
  image: sdesbure/yamllint
  stage: linting
  script:
    - yamllint .
