---
# git commit -m "ci/cd" --no-verify
# run --all-files
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: ["-c=/mnt/c/vagrant/Ansible/vagrant-ansible-docker/.config/.yamllint", "."]
