---
# git commit -m "ci/cd" --no-verify
# pre-commit run --all-files
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: ["-c=/mnt/c/vagrant/Ansible/vagrant-ansible-docker/.yamllint", "."]

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.2.2
    hooks:
      - id: ansible-lint
        args: [-c=/mnt/c/vagrant/Ansible/vagrant-ansible-docker/.config/.ansible-lint]
