---
# tasks file for sys-common
- name: Create group
  group:
    name: "sysadmin"
    gid: 666
    state: present

- name: Create Users Task
  user:
    name: "sysadmin"
    uid: 666
    state: present
    shell: /bin/bash
    group: "sysadmin"

- name: Add sysadmin as sudoer user
  lineinfile:
    dest: /etc/sudoers
    state: present
    backup: yes
    regexp: '^sysadmin ALL\='
    line: 'sysadmin ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: Update apt cache if needed.
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
