---
version: "3.3"

services :

  # CONTAINER - MYSQL : https://hub.docker.com/_/mysql
  db:
    image: mariadb:latest
    container_name: wp_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $mysql_root_pswd
      MYSQL_DATABASE: $mysql_database
      MYSQL_USER: $mysql_user
      MYSQL_PASSWORD: $mysql_password
    networks:
      - wp

  # CONTAINER - WORDPRESS : https://hub.docker.com/_/wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_wordpress
    restart: always
    volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $wp_db_user
      WORDPRESS_DB_PASSWORD: $wp_db_password
    ports:
      - "80:80"
    networks:
      - wp

networks:
  wp:

volumes:
  db_data:
